version: '3'

services:

  client:
    container_name: controle-estoque-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    restart: unless-stopped
    env_file: .env

  nginx:
    container_name: controle-estoque-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3050:80
    depends_on:
      - client
