version: '3'

services:

  app:
    container_name: controle-estoque
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    environment:
      - PORT=$NODE_DOCKER_PORT
    ports:
      - 3020:$NODE_DOCKER_PORT
    restart: unless-stopped
    env_file: .env
    depends_on:
      - database

  database:
    container_name: controle-estoque-db
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - db_config:/etc/mysql
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - TIMEZONE=$MYSQL_TIMEZONE
    ports:
      - 3306:$MYSQL_DOCKER_PORT
    restart: unless-stopped
    env_file: .env

volumes:
  db_config:
  db_data:
